defaults: &defaults
  adapter: mysql2
  username: root
  password: '177591'
  host: localhost  

development:
  <<: *defaults
  database: rails_tester_dev

test:
  <<: *defaults
  database: rails_tester_test
